# Generated by Django 2.1.7 on 2020-08-15 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200808_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 15, 16, 30, 2, 866709)),
        ),
    ]
