# Generated by Django 2.1.7 on 2020-08-15 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200815_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 15, 16, 34, 36, 782849)),
        ),
    ]
